import { _electron as electron, expect } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

const root = path.resolve(import.meta.dirname, '..');
const outputs = path.join(root, 'test-results');
await fs.mkdir(outputs, { recursive: true });
const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'shixu-smoke-'));
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const errors = [];
const packaged = process.argv.includes('--packaged');
let app;
const report = [];
const record = (message) => { report.push(message); console.log(`PASS ${message}`); };
async function launch() {
  app = await electron.launch({ ...(packaged ? { executablePath: path.join(root, 'release/win-unpacked/拾序.exe') } : {}), args: [...(packaged ? [] : [root]), `--data-dir=${dataDir}`, '--force-device-scale-factor=1'], env, timeout: 30000 });
  const page = await app.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  await expect(page.getByRole('heading', { name: '今天', exact: true })).toBeVisible();
  await expect(page.getByText('已保存到本地', { exact: true })).toBeVisible();
  return page;
}
try {
  let page = await launch();
  await page.screenshot({ path: path.join(outputs, '01-today-light.png') });
  record('桌面启动与本地保存');
  await page.getByLabel('快速添加任务', { exact: true }).fill('验收：准备明天的计划');
  await page.getByLabel('快速添加任务', { exact: true }).press('Enter');
  await expect(page.getByRole('button', { name: '编辑任务 验收：准备明天的计划', exact: true })).toBeVisible();
  record('快捷录入任务');
  await page.getByRole('button', { name: '编辑任务 验收：准备明天的计划', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '任务详情' });
  await dialog.getByLabel('任务名称', { exact: true }).fill('验收：完成设计稿');
  await dialog.getByLabel('所属清单').selectOption('work');
  await dialog.getByLabel('优先级', { exact: true }).selectOption('3');
  await dialog.getByLabel('开始时间').fill('15:30');
  await dialog.getByLabel('预计时长').fill('90');
  await dialog.getByLabel('任务备注').fill('桌面自动化检查：中文输入与持久化。');
  await dialog.getByLabel('添加子任务', { exact: true }).fill('检查留白与排版');
  await dialog.getByLabel('添加子任务', { exact: true }).press('Enter');
  await page.screenshot({ path: path.join(outputs, '02-task-editor.png') });
  await dialog.getByRole('button', { name: '保存更改', exact: true }).click();
  await expect(page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true }).click();
  await expect(dialog.getByLabel('所属清单')).toHaveValue('work');
  await expect(dialog.getByLabel('优先级', { exact: true })).toHaveValue('3');
  await expect(dialog.getByLabel('预计时长')).toHaveValue('90');
  await page.getByRole('button', { name: '关闭弹窗', exact: true }).click();
  record('编辑日期、清单、优先级、时长、备注、子任务');
  await page.getByRole('checkbox', { name: '完成 验收：完成设计稿', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: '恢复 验收：完成设计稿', exact: true })).toBeChecked();
  await page.getByRole('checkbox', { name: '恢复 验收：完成设计稿', exact: true }).click();
  record('完成与恢复任务');
  await page.keyboard.press('Control+k');
  await page.getByLabel('搜索全部任务').fill('中文输入与持久化');
  await expect(page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true })).toBeVisible();
  record('键盘搜索备注');
  await page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true }).click();
  await page.getByRole('button', { name: '删除任务', exact: true }).click();
  await expect(page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  await expect(page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true })).toBeVisible();
  record('删除与撤销');
  await page.getByRole('button', { name: '新建清单', exact: true }).click();
  await page.getByLabel('清单名称', { exact: true }).fill('验收清单');
  await page.getByRole('button', { name: '绿色', exact: true }).click();
  await page.getByRole('button', { name: '创建清单', exact: true }).click();
  await page.getByRole('button', { name: '验收清单', exact: true }).click();
  await page.getByLabel('快速添加任务', { exact: true }).fill('清单迁移测试');
  await page.getByLabel('快速添加任务', { exact: true }).press('Enter');
  await page.getByRole('button', { name: '编辑清单 验收清单', exact: true }).click();
  await page.getByRole('button', { name: '删除清单', exact: true }).click();
  await page.getByRole('dialog', { name: '删除这个清单？' }).getByRole('button', { name: '删除清单', exact: true }).click();
  await expect(page.getByRole('button', { name: '编辑任务 清单迁移测试', exact: true })).toBeVisible();
  record('创建清单与删除后的任务迁移');
  await page.getByRole('button', { name: '日历', exact: true }).click();
  await expect(page.getByRole('heading', { name: '日历', exact: true })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.querySelector('.app-window').scrollTop)).toBe(0);
  await page.screenshot({ path: path.join(outputs, '03-calendar-week.png') });
  const target = page.locator('.time-slot').filter({ hasNotText: 'unused' }).nth(25);
  const targetLabel = await target.getAttribute('aria-label');
  await target.click();
  await page.getByLabel('任务名称', { exact: true }).fill('点击时段创建日程');
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  await expect(page.locator('.week-event').filter({ hasText: '点击时段创建日程' })).toBeVisible();
  record(`周日历点击时段创建：${targetLabel}`);
  const sourceEvent = page.locator('.week-event').filter({ hasText: '点击时段创建日程' });
  const dropTarget = page.locator('.time-slot').nth(48 + 26);
  const dropLabel = await dropTarget.getAttribute('aria-label');
  await sourceEvent.dragTo(dropTarget);
  await expect(sourceEvent).toContainText('13:00');
  await sourceEvent.click();
  await expect(page.getByLabel('计划日期')).toHaveValue(dropLabel.split(' ')[1]);
  await expect(page.getByLabel('开始时间')).toHaveValue('13:00');
  await page.getByRole('button', { name: '关闭弹窗', exact: true }).click();
  record('拖动日程到次日并修改开始时间');
  await page.getByRole('button', { name: '月', exact: true }).click();
  await expect(page.locator('.month-cell')).toHaveCount(42);
  await page.screenshot({ path: path.join(outputs, '04-calendar-month.png') });
  record('月日历 42 天视图');
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('button', { name: '深色', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('button', { name: '关闭弹窗', exact: true }).click();
  await page.getByRole('button', { name: '今天', exact: true }).first().click();
  await page.screenshot({ path: path.join(outputs, '05-today-dark.png') });
  record('深色主题');
  await expect(page.getByText('已保存到本地', { exact: true })).toBeVisible();
  await app.close(); app = null;
  page = await launch();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '编辑任务 验收：完成设计稿', exact: true }).click();
  await expect(page.getByLabel('任务备注')).toHaveValue('桌面自动化检查：中文输入与持久化。');
  await expect(page.getByLabel('预计时长')).toHaveValue('90');
  await expect(page.getByLabel('子任务名称 检查留白与排版', { exact: true })).toHaveValue('检查留白与排版');
  record('关闭重启后任务、子任务、备注与主题持久化');
  await page.getByRole('button', { name: '关闭弹窗', exact: true }).click();
  await page.getByRole('button', { name: '设置', exact: true }).click();
  const exportPath = path.join(dataDir, 'exported-backup.json');
  await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, exportPath);
  await page.getByRole('button', { name: '导出备份', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('备份已导出');
  const exported = JSON.parse(await fs.readFile(exportPath, 'utf8'));
  expect(exported.tasks.some(task => task.title === '验收：完成设计稿')).toBe(true);
  record('原生 JSON 备份导出');
  const invalidPath = path.join(dataDir, 'invalid-backup.json');
  await fs.writeFile(invalidPath, JSON.stringify({ version: 99, tasks: [] }));
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, invalidPath);
  await page.getByRole('button', { name: '导入备份', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('无法导入');
  record('非法备份不会覆盖当前记录');
  exported.tasks[0].title = '备份恢复验证';
  const restorePath = path.join(dataDir, 'restore-backup.json');
  await fs.writeFile(restorePath, JSON.stringify(exported));
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, restorePath);
  await page.getByRole('button', { name: '导入备份', exact: true }).click();
  await page.getByRole('button', { name: '恢复备份', exact: true }).click();
  await page.getByRole('button', { name: '关闭弹窗', exact: true }).click();
  await expect(page.getByRole('button', { name: '编辑任务 备份恢复验证', exact: true })).toBeVisible();
  record('确认导入后正确替换数据');
  await expect(page.getByText('已保存到本地', { exact: true })).toBeVisible();
  const backupBeforeCorrupt = JSON.parse(await fs.readFile(path.join(dataDir, 'shixu-data.json.backup'), 'utf8'));
  await app.close(); app = null;
  await fs.writeFile(path.join(dataDir, 'shixu-data.json'), '{broken json');
  page = await launch();
  await expect(page.getByRole('status')).toContainText('已从上一份备份恢复');
  const restoredOnDisk = JSON.parse(await fs.readFile(path.join(dataDir, 'shixu-data.json'), 'utf8'));
  expect(restoredOnDisk.tasks.length).toBe(backupBeforeCorrupt.tasks.length);
  expect((await fs.readdir(dataDir)).some(name => name.includes('.corrupted-'))).toBe(true);
  record('损坏主文件自动恢复备份，保留损坏原件');
  expect(errors).toEqual([]);
  record('渲染进程无未捕获异常');
  await fs.writeFile(path.join(outputs, packaged ? 'packaged-report.json' : 'desktop-report.json'), JSON.stringify({ passed: report, errors, dataDir, packaged }, null, 2));
} catch (error) {
  if (app) { const pages = app.windows(); if (pages[0]) await pages[0].screenshot({ path: path.join(outputs, 'failure.png') }).catch(() => {}); }
  throw error;
} finally { if (app) await app.close(); }
