import { _electron as electron, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

const root = path.resolve(import.meta.dirname, '..');
const outputs = path.join(root, 'test-results');
await fs.mkdir(outputs, { recursive: true });
const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'dayloom-planning-'));
const dataFile = path.join(dataDir, 'shixu-data.json');
await fs.writeFile(dataFile, JSON.stringify({ version: 1, lists: [{ id: 'inbox', name: '收集箱', color: '#8996aa' }], tasks: [], settings: { theme: 'light', glass: 82 } }));
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const packaged = process.argv.includes('--packaged');
const errors = [], checks = [];
const record = message => { checks.push(message); console.log(`PASS ${message}`); };
let app, page;
async function launch() {
  app = await electron.launch({ ...(packaged ? { executablePath: path.join(root, 'release/win-unpacked/拾序.exe') } : {}), args: [...(packaged ? [] : [root]), `--data-dir=${dataDir}`, '--force-device-scale-factor=1'], env, timeout: 30000 });
  page = await app.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  await expect(page.getByRole('heading', { name: '今天', exact: true })).toBeVisible();
  await page.clock.install({ time: new Date('2026-10-07T12:00:00+08:00') });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.reload();
  await expect(page.getByRole('heading', { name: '今天', exact: true })).toBeVisible();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1400, 960));
}
const button = name => name === '今天' ? page.getByRole('navigation', { name: '智能清单' }).getByRole('button', { name, exact: true }) : page.getByRole('button', { name, exact: true });
const label = name => page.getByLabel(name, { exact: true });
const row = title => page.locator('.task-row').filter({ has: button(`编辑任务 ${title}`) });
const saved = () => expect(page.getByText('已保存到本地', { exact: true })).toBeVisible();
const read = async () => JSON.parse(await fs.readFile(dataFile, 'utf8'));
try {
  await launch();
  await button('周期事务').click();
  await button('创建第一个事务').click();
  await expect(label('分组类型')).toHaveValue('routine');
  await expect(label('时间基准')).toHaveValue('local');
  await expect(label('每日刷新时间')).toHaveValue('00:00');
  await label('分组名称').fill('生活与学习');
  await button('保存分组').click();
  await label('事务名称').fill('每日阅读');
  await expect(label('周期时间安排')).toHaveValue('anytime');
  await expect(label('活动计划时间')).toHaveCount(0);
  await button('创建事务').click();
  for (const [title, kind] of [['每周复盘', 'weekly'], ['月度整理', 'monthly']]) {
    await button('新建事务').click();
    await label('事务名称').fill(title);
    await label('重复规则').selectOption(kind);
    await button('创建事务').click();
  }
  await button('新建事务').click();
  await label('事务名称').fill('周三和周五运动');
  await label('重复规则').selectOption('material');
  for (const name of ['星期一执行', '星期四执行', '星期日执行', '星期三执行', '星期五执行']) await button(name).click();
  await label('周期时间安排').selectOption('window');
  await label('周期最早时间').fill('18:00');
  await label('周期最晚时间').fill('21:00');
  await page.screenshot({ path: path.join(outputs, 'planning-routine-editor.png') });
  await button('创建事务').click();
  await expect(page.locator('.game-activity-card')).toHaveCount(4);
  await button('今天').click();
  await expect(page.locator('.routine-row')).toHaveCount(4);
  const reading = page.locator('.routine-row').filter({ hasText: '每日阅读' });
  await reading.getByRole('button', { name: '完成', exact: true }).click();
  await expect(reading.getByRole('button', { name: '已完成', exact: true })).toBeVisible();
  record('普通分组按本机午夜刷新；每天、指定星期、周、月事务均可创建并在今天推进');

  await expect(button('重要不紧急')).toHaveCount(0);
  await button('新建任务').click();
  await label('优先级').selectOption('4');
  await label('任务名称').fill('准备明年的资格考试');
  await button('时间窗口').click();
  await label('最早日期').fill('');
  await expect(button('创建任务')).toBeDisabled();
  await label('最晚日期').fill('2027-06-01');
  await expect(label('开始时间')).toHaveCount(0);
  await expect(label('预计时长')).toHaveCount(0);
  await button('创建任务').click();
  await expect(row('准备明年的资格考试')).toContainText('非常重要');
  await expect(page.getByRole('checkbox', { name: '完成 准备明年的资格考试', exact: true })).not.toBeChecked();
  await expect(row('准备明年的资格考试')).not.toHaveClass(/is-complete/);
  await button('今天').click();
  await expect(row('准备明年的资格考试')).toBeVisible();
  await saved();
  let stored = await read();
  assert.equal(stored.tasks[0].completed, false);
  assert.equal(stored.tasks[0].priority, 4);
  assert.equal(stored.tasks[0].longTerm, undefined);
  assert.equal(stored.tasks[0].timeWindow.earliest, null);
  record('取消独立栏目；非常重要任务只有远期截止日期也会显示在今天');

  await button('新建任务').click();
  await label('任务名称').fill('整理项目资料');
  await button('时间窗口').click();
  await label('最早日期').fill('2026-10-07');
  await label('最早时间').fill('09:00');
  await label('最晚日期').fill('2026-10-09');
  await label('最晚时间').fill('18:00');
  await page.screenshot({ path: path.join(outputs, 'planning-task-window.png') });
  await label('最晚日期').fill('2026-10-06');
  await expect(button('创建任务')).toBeDisabled();
  await expect(page.getByRole('alert')).toContainText('不能早于');
  await label('最晚日期').fill('2026-10-09');
  await button('创建任务').click();
  await expect(row('整理项目资料')).toContainText('待安排');
  await button('日历').click();
  await expect(page.locator('.all-day-cell .calendar-pill').filter({ hasText: '整理项目资料' })).toHaveCount(3);
  await expect(page.locator('.week-event').filter({ hasText: '整理项目资料' })).toHaveCount(0);
  const floating = page.locator('.all-day-cell .calendar-pill').filter({ hasText: '整理项目资料' }).first();
  await floating.dragTo(button('安排 2026-10-07 08:30'));
  await expect(page.getByRole('status')).toContainText('时间窗口');
  await expect(page.locator('.week-event').filter({ hasText: '整理项目资料' })).toHaveCount(0);
  await floating.dragTo(button('安排 2026-10-07 09:00'));
  await expect(page.locator('.week-event').filter({ hasText: '整理项目资料' })).toHaveCount(1);
  await page.locator('.week-event').filter({ hasText: '整理项目资料' }).click();
  await expect(label('开始时间')).toHaveValue('09:00');
  await expect(label('最晚日期')).toHaveValue('2026-10-09');
  await page.getByRole('checkbox', { name: '设置具体安排', exact: true }).uncheck();
  await button('保存更改').click();
  await expect(page.locator('.all-day-cell .calendar-pill').filter({ hasText: '整理项目资料' })).toHaveCount(3);
  record('时间窗口在待安排区显示；拖动越界被拦截，范围内排期及取消具体安排保留窗口');

  const exercise = page.locator('.all-day-cell .calendar-pill').filter({ hasText: '周三和周五运动' }).first();
  await exercise.click();
  await expect(page.getByRole('dialog', { name: '本期安排', exact: true })).toContainText('18:00');
  await page.getByRole('checkbox', { name: '暂不指定时刻（显示在待安排区）', exact: true }).uncheck();
  await label('本期计划时间').fill('17:00');
  await button('保存本期安排').click();
  await expect(page.getByRole('status')).toContainText('本期的时间窗口');
  await label('本期计划时间').fill('19:00');
  await button('保存本期安排').click();
  await expect(button('已保存安排')).toBeVisible();
  await button('关闭弹窗').click();
  await expect(page.locator('.week-event').filter({ hasText: '周三和周五运动' })).toHaveCount(1);
  await button('月').click();
  await expect(page.locator('.month-events .calendar-pill').filter({ hasText: '整理项目资料' })).toHaveCount(3);
  record('周期事务支持时间窗口和单期排期，月历也显示浮动任务');

  await button('今天').click();
  await saved();
  if (await button('关闭提示').count()) await button('关闭提示').click();
  await page.screenshot({ path: path.join(outputs, 'planning-today-light.png') });
  await app.close();
  await launch();
  await expect(row('准备明年的资格考试')).toContainText('非常重要');
  await expect(row('整理项目资料')).toContainText('待安排');
  await expect(page.locator('.routine-row').filter({ hasText: '每日阅读' }).getByRole('button', { name: '已完成', exact: true })).toBeVisible();
  record('重启后恢复非常重要属性、时间窗口与周期完成记录');

  await page.clock.fastForward(12 * 3600000 + 2000);
  await expect(page.getByRole('checkbox', { name: '完成 准备明年的资格考试', exact: true })).not.toBeChecked();
  await expect(row('准备明年的资格考试')).toContainText('非常重要');
  await expect(page.locator('.routine-row').filter({ hasText: '每日阅读' }).getByRole('button', { name: '完成', exact: true })).toBeVisible();
  await expect(page.locator('.routine-row').filter({ hasText: '周三和周五运动' })).toHaveCount(0);
  await page.getByRole('checkbox', { name: '完成 准备明年的资格考试', exact: true }).click();
  await expect(row('准备明年的资格考试')).toHaveClass(/is-complete/);
  await page.clock.fastForward(24 * 3600000);
  await expect(row('准备明年的资格考试')).toHaveCount(0);
  await button('已完成').click();
  await expect(row('准备明年的资格考试')).toHaveClass(/is-complete/);
  await page.getByRole('checkbox', { name: '恢复 准备明年的资格考试', exact: true }).click();
  await button('今天').click();
  await expect(row('准备明年的资格考试')).toContainText('非常重要');
  record('非常重要任务跨天继续显示；勾选完成后次日停止显示，恢复后重新每天出现');

  await button('设置').click();
  await button('深色').click();
  await button('关闭弹窗').click();
  await page.screenshot({ path: path.join(outputs, 'planning-important-dark.png') });
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 740));
  await expect.poll(() => page.evaluate(() => document.querySelector('.task-main').scrollWidth <= document.querySelector('.task-main').clientWidth)).toBe(true);
  await button('编辑任务 准备明年的资格考试').click();
  await page.screenshot({ path: path.join(outputs, 'planning-window-compact-dark.png') });
  await expect(button('保存更改')).toBeVisible();
  await button('关闭弹窗').click();
  await saved();
  stored = await read();
  assert.equal(stored.tasks.length, 2);
  assert.equal(stored.tasks[0].priority, 4);
  assert.equal(stored.tasks[0].longTerm, undefined);
  assert.equal(stored.gaming.games[0].category, 'routine');
  assert.equal(stored.gaming.activities.length, 4);
  assert.equal(stored.tasks[1].date, null);
  assert.equal(stored.tasks[1].time, null);
  assert.deepEqual(errors, []);
  record('浅深主题、紧凑窗口、持久化字段与无重复任务验证');
  await fs.writeFile(path.join(outputs, packaged ? 'planning-packaged-report.json' : 'planning-smoke-report.json'), JSON.stringify({ passed: checks.length, checks, errors, dataDir }, null, 2));
} catch (error) {
  try { await page.screenshot({ path: path.join(outputs, 'planning-failure.png') }); } catch {}
  throw error;
} finally { if (app) await app.close().catch(() => {}); }
