import { useState } from 'react';
import { Check, Gamepad2, Plus, Trash2 } from 'lucide-react';
import { COLORS, dateKey, WEEKDAYS } from '../domain';
import { changeProgress, gameDay, gamingData, KIND_NAMES, localTime, newActivity, newGame, planOccurrence, remainingLabel, removeActivity, removeGame, resolveOccurrence, ruleLabel, saveActivity, saveGame, zoneLabel } from '../gaming';
import type { GameOccurrence, OccurrenceRef } from '../gaming';
import type { ActivityKind, AppData, GameActivity, GameProfile } from '../types';
import { accentStyle, Confirm, Modal } from './ui';

export type GameDialog = { kind: 'games' } | { kind: 'game'; game?: GameProfile; addAfter?: boolean } | { kind: 'activity'; activity: GameActivity; isNew: boolean } | { kind: 'occurrence'; ref: OccurrenceRef };
export type DataUpdate = (fn: (data: AppData) => AppData) => boolean;
export function GameDialogs({ dialog, data, now, onDialog, update }: { dialog: GameDialog; data: AppData; now: Date; onDialog: (dialog: GameDialog | null) => void; update: DataUpdate }) {
  const close = () => onDialog(null), gaming = gamingData(data);
  if (dialog.kind === 'games') return <Modal title="我的游戏" description="按游戏服务器设置时区和刷新时间。" onClose={close} className="game-form-modal"><div className="game-manager">{gaming.games.map(game => <button key={game.id} style={accentStyle(game.color)} onClick={() => onDialog({ kind: 'game', game })}><span className="game-avatar"><Gamepad2 size={21} /></span><span><strong>{game.name}</strong><small>{zoneLabel(game.utcOffset)} · 每天 {game.resetTime} 刷新</small></span><span>编辑</span></button>)}{!gaming.games.length && <p className="game-hint">先添加一个游戏，再为它安排活动。</p>}</div><div className="modal-actions"><button className="button primary" onClick={() => onDialog({ kind: 'game' })}><Plus size={16} />添加游戏</button></div></Modal>;
  if (dialog.kind === 'game') return <GameForm key={dialog.game?.id || 'new'} game={dialog.game} onClose={close} onSave={game => { if (update(data => saveGame(data, game))) onDialog(dialog.addAfter ? { kind: 'activity', activity: newActivity(game, now), isNew: true } : null); }} onDelete={id => { if (update(data => removeGame(data, id))) close(); }} />;
  if (dialog.kind === 'activity') return <ActivityForm key={dialog.activity.id} activity={dialog.activity} isNew={dialog.isNew} games={gaming.games} now={now} onClose={close} onSave={activity => { if (update(data => saveActivity(data, activity))) close(); }} onDelete={id => { if (update(data => removeActivity(data, id))) close(); }} />;
  const item = resolveOccurrence(data, dialog.ref);
  if (!item) return <Modal title="活动已变更" onClose={close}><p className="confirm-description">该活动已暂停、删除或修改了刷新规则，请从游戏日程重新打开。</p><div className="modal-actions"><button className="button primary" onClick={close}>知道了</button></div></Modal>;
  return <OccurrenceForm key={JSON.stringify(dialog.ref)} item={item} now={now} onClose={close} onEdit={() => onDialog({ kind: 'activity', activity: item.activity, isNew: false })} onProgress={count => update(data => changeProgress(data, item.ref, count, new Date()))} onPlan={(day, time) => update(data => planOccurrence(data, item.ref, day, time))} />;
}

function GameForm({ game, onClose, onSave, onDelete }: { game?: GameProfile; onClose: () => void; onSave: (game: GameProfile) => void; onDelete: (id: string) => void }) {
  const [initial] = useState(() => game || newGame());
  const [draft, setDraft] = useState(initial);
  const [confirm, setConfirm] = useState<'discard' | 'delete' | null>(null);
  const patch = (value: Partial<GameProfile>) => setDraft(current => ({ ...current, ...value }));
  const dirty = JSON.stringify(draft) !== JSON.stringify(initial);
  const ruleChanged = game && (game.utcOffset !== draft.utcOffset || game.resetTime !== draft.resetTime || game.weekResetDay !== draft.weekResetDay || game.monthResetDay !== draft.monthResetDay);
  return <><Modal title={game ? '编辑游戏' : '添加游戏'} description="按游戏服务器设置刷新时间；计划会自动换算到本机日历。" onClose={() => dirty ? setConfirm('discard') : onClose()} className="game-form-modal"><form onSubmit={event => { event.preventDefault(); if (draft.name.trim()) onSave({ ...draft, name: draft.name.trim() }); }}>
    <div className="game-form-scroll"><label className="form-label">游戏名称<input data-autofocus aria-label="游戏名称" placeholder="例如：正在玩的冒险游戏" required maxLength={40} value={draft.name} onChange={event => patch({ name: event.target.value })} /></label>
    <div className="form-label">标记颜色<div className="color-choices">{COLORS.map((color, index) => <button type="button" key={color} aria-label={`游戏颜色 ${index + 1}`} aria-pressed={color === draft.color} style={{ background: color }} onClick={() => patch({ color })}>{draft.color === color && <Check size={18} />}</button>)}</div></div>
    <div className="game-fields"><label className="form-label">服务器时区<select aria-label="服务器时区" value={draft.utcOffset} onChange={event => patch({ utcOffset: Number(event.target.value) })}>{Array.from({ length: 105 }, (_, index) => index * 15 - 720).map(offset => <option key={offset} value={offset}>{zoneLabel(offset)}{offset === 480 ? '（北京时间）' : ''}</option>)}</select></label><label className="form-label">每日刷新时间<input aria-label="每日刷新时间" type="time" required value={draft.resetTime} onChange={event => patch({ resetTime: event.target.value })} /></label>
    <label className="form-label">周常刷新日<select aria-label="周常刷新日" value={draft.weekResetDay} onChange={event => patch({ weekResetDay: Number(event.target.value) })}>{[1, 2, 3, 4, 5, 6, 0].map(day => <option key={day} value={day}>星期{WEEKDAYS[day]}</option>)}</select></label><label className="form-label">月常刷新日<select aria-label="月常刷新日" value={draft.monthResetDay} onChange={event => patch({ monthResetDay: Number(event.target.value) })}>{Array.from({ length: 31 }, (_, index) => <option key={index} value={index + 1}>每月 {index + 1} 日</option>)}</select></label></div>
    <p className="game-hint">周常、月常均在上方时间刷新。选择 29–31 日时，较短的月份自动使用月末。时区是固定偏移，不跟随夏令时。</p>
    {ruleChanged && <p className="game-rule-notice">修改刷新规则后，该游戏的活动将按新周期重新计数。此前完成记录仍会保留。</p>}</div>
    <div className="modal-actions">{game && <button type="button" className="button text-danger" onClick={() => setConfirm('delete')}><Trash2 size={16} />删除游戏</button>}<button className="button primary" type="submit" disabled={!draft.name.trim()}>保存游戏</button></div>
  </form></Modal>{confirm && <Confirm title={confirm === 'delete' ? '删除这个游戏？' : '放弃未保存的更改？'} description={confirm === 'delete' ? '该游戏的全部活动和完成记录都会删除。' : '离开后，本次编辑的内容不会保存。'} action={confirm === 'delete' ? '删除游戏' : '放弃更改'} danger={confirm === 'delete'} onClose={() => setConfirm(null)} onConfirm={() => confirm === 'delete' ? onDelete(game!.id) : onClose()} />}</>;
}

function ActivityForm({ activity, isNew, games, now, onClose, onSave, onDelete }: { activity: GameActivity; isNew: boolean; games: GameProfile[]; now: Date; onClose: () => void; onSave: (activity: GameActivity) => void; onDelete: (id: string) => void }) {
  const [draft, setDraft] = useState(() => structuredClone(activity));
  const [confirm, setConfirm] = useState<'discard' | 'delete' | null>(null);
  const patch = (value: Partial<GameActivity>) => setDraft(current => ({ ...current, ...value }));
  const game = games.find(item => item.id === draft.gameId)!;
  const dirty = JSON.stringify(draft) !== JSON.stringify(activity);
  const ruleChanged = !isNew && (draft.gameId !== activity.gameId || draft.kind !== activity.kind || [...draft.weekdays].sort().join() !== [...activity.weekdays].sort().join());
  return <><Modal title={isNew ? '新建游戏活动' : '编辑活动规则'} description="按刷新周期重复，完成次数每期独立记录。" onClose={() => dirty ? setConfirm('discard') : onClose()} className="game-form-modal"><form onSubmit={event => { event.preventDefault(); if (draft.title.trim() && (draft.kind !== 'material' || draft.weekdays.length)) onSave(draft); }}>
    <div className="game-form-scroll"><label className="form-label">活动名称<input data-autofocus aria-label="活动名称" required maxLength={150} placeholder="例如：角色天赋材料、每周首领" value={draft.title} onChange={event => patch({ title: event.target.value })} /></label>
    <div className="game-fields"><label className="form-label">所属游戏<select aria-label="所属游戏" value={draft.gameId} onChange={event => { const next = games.find(game => game.id === event.target.value)!; patch({ gameId: next.id, startDate: next.id === activity.gameId ? activity.startDate : gameDay(next, now) }); }}>{games.map(game => <option key={game.id} value={game.id}>{game.name}</option>)}</select></label><label className="form-label">活动类型<select aria-label="活动类型" value={draft.kind} onChange={event => patch({ kind: event.target.value as ActivityKind })}>{Object.entries(KIND_NAMES).map(([kind, name]) => <option key={kind} value={kind}>{name}</option>)}</select></label></div>
    {draft.kind === 'material' && <fieldset className="weekday-field"><legend>材料本开放日</legend><div className="weekday-choices">{[1, 2, 3, 4, 5, 6, 0].map(day => <button type="button" key={day} aria-label={`星期${WEEKDAYS[day]}开放`} aria-pressed={draft.weekdays.includes(day)} onClick={() => patch({ weekdays: draft.weekdays.includes(day) ? draft.weekdays.filter(value => value !== day) : [...draft.weekdays, day] })}>周{WEEKDAYS[day]}</button>)}</div>{!draft.weekdays.length && <p className="field-error">至少选择一个开放日。</p>}</fieldset>}
    <div className="game-fields"><label className="form-label">{draft.kind === 'material' ? '每次开放日目标' : '每个周期目标'}<span className="game-unit-input"><input aria-label="目标次数" type="number" required min={1} max={99} value={draft.target} onChange={event => patch({ target: Number(event.target.value) })} /><span>次</span></span></label><label className="form-label">计划时间 · {zoneLabel(game.utcOffset)}<input aria-label="活动计划时间" type="time" required value={draft.planTime} onChange={event => patch({ planTime: event.target.value })} /></label>
    {draft.kind === 'weekly' && <label className="form-label">每周计划日<select aria-label="每周计划日" value={draft.planWeekday} onChange={event => patch({ planWeekday: Number(event.target.value) })}>{[1, 2, 3, 4, 5, 6, 0].map(day => <option key={day} value={day}>星期{WEEKDAYS[day]}</option>)}</select></label>}
    {draft.kind === 'monthly' && <label className="form-label">每月计划日<select aria-label="每月计划日" value={draft.planMonthDay} onChange={event => patch({ planMonthDay: Number(event.target.value) })}>{Array.from({ length: 31 }, (_, index) => <option key={index} value={index + 1}>{index + 1} 日</option>)}</select></label>}
    <label className="form-label">单次预计用时<span className="game-unit-input"><input aria-label="单次预计用时" type="number" min={1} max={720} required value={draft.minutes} onChange={event => patch({ minutes: Number(event.target.value) })} /><span>分钟</span></span></label><label className="form-label">单次体力消耗<span className="game-unit-input"><input aria-label="单次体力消耗" type="number" min={0} max={999} required value={draft.energy} onChange={event => patch({ energy: Number(event.target.value) })} /><span>点</span></span></label></div>
    <p className="game-hint">{draft.kind === 'material' ? '开放日按游戏日计算，每个开放日独立记录次数。' : `在${draft.kind === 'daily' ? '每天' : draft.kind === 'weekly' ? `每周${WEEKDAYS[game.weekResetDay]}` : `每月 ${game.monthResetDay} 日`} ${game.resetTime} 刷新。`}{draft.planTime < game.resetTime ? '计划时间早于刷新时间，会安排在该游戏日的次日凌晨。' : ''}{draft.kind === 'monthly' ? '短月份使用月末；本期计划日已过时，新活动从今天安排。' : ''} 体力填 0 表示不计。</p>
    <label className="form-label">备注<textarea aria-label="活动备注" rows={3} maxLength={5000} placeholder="想培养的角色、需要的材料，或兑换清单…" value={draft.notes} onChange={event => patch({ notes: event.target.value })} /></label>
    {ruleChanged && <p className="game-rule-notice">开放日、类型或游戏变更后，活动将按新规则重新计算进度。仅修改名称、目标或计划时间会保留进度。</p>}</div>
    <div className="modal-actions">{!isNew && <button type="button" className="button text-danger" onClick={() => setConfirm('delete')}><Trash2 size={16} />删除活动</button>}<button className="button primary" type="submit" disabled={!draft.title.trim() || (draft.kind === 'material' && !draft.weekdays.length)}>{isNew ? '创建活动' : '保存活动'}</button></div>
  </form></Modal>{confirm && <Confirm title={confirm === 'delete' ? '删除这个活动？' : '放弃未保存的更改？'} description={confirm === 'delete' ? '活动规则及其所有完成记录都会删除。' : '离开后，本次编辑的内容不会保存。'} action={confirm === 'delete' ? '删除活动' : '放弃更改'} danger={confirm === 'delete'} onClose={() => setConfirm(null)} onConfirm={() => confirm === 'delete' ? onDelete(activity.id) : onClose()} />}</>;
}

export function ProgressControls({ item, now, onChange }: { item: GameOccurrence; now: Date; onChange: (count: number) => void }) {
  const active = now >= item.start && now < item.end && gameDay(item.game, now) >= item.activity.startDate;
  return <div className="game-progress-controls"><button aria-label={`减少完成次数 ${item.activity.title}`} disabled={!active || !item.count} onClick={() => onChange(item.count - 1)}>−</button><span aria-label="完成进度">{item.count}<small> / {item.activity.target}</small></span><button aria-label={`增加完成次数 ${item.activity.title}`} disabled={!active || item.count >= item.activity.target} onClick={() => onChange(item.count + 1)}>＋</button><button className={`game-complete ${item.count >= item.activity.target ? 'is-complete' : ''}`} disabled={!active} onClick={() => onChange(item.count >= item.activity.target ? 0 : item.activity.target)}><Check size={15} />{item.count >= item.activity.target ? '已完成' : '完成'}</button></div>;
}

function OccurrenceForm({ item, now, onClose, onEdit, onProgress, onPlan }: { item: GameOccurrence; now: Date; onClose: () => void; onEdit: () => void; onProgress: (count: number) => void; onPlan: (day: string, time: string | null) => boolean }) {
  const [day, setDay] = useState(dateKey(item.plannedAt));
  const [time, setTime] = useState(localTime(item.plannedAt));
  const [allDay, setAllDay] = useState(item.allDay);
  const [saved, setSaved] = useState(false);
  const format = (at: Date) => `${dateKey(at)} ${localTime(at)}`;
  return <Modal title="活动安排" description={`${item.game.name} · ${KIND_NAMES[item.activity.kind]}`} onClose={onClose} className="game-form-modal"><div className="game-occurrence-detail" style={accentStyle(item.game.color)}><h3>{item.activity.title}</h3><p className="game-hint">{ruleLabel(item.activity)} · 每次 {item.activity.minutes} 分钟{item.activity.energy ? ` · ${item.activity.energy} 体力` : ''}</p><div className="game-cycle-info"><span>本期开放（本机时间）</span><strong>{format(item.start)} — {format(item.end)}</strong><small>{now < item.start ? '尚未开放，可提前安排时间' : remainingLabel(item.end, now)}</small></div><ProgressControls item={item} now={now} onChange={onProgress} />{item.activity.notes && <p className="game-detail-notes">{item.activity.notes}</p>}
    <form onSubmit={event => { event.preventDefault(); if (onPlan(day, allDay ? null : time)) setSaved(true); }}><h4>本期计划</h4><p className="game-hint">按本机时区安排，仅调整这一次；请放在上方开放区间内。</p><div className="game-fields"><label className="form-label">日期<input aria-label="本期计划日期" required type="date" min="1900-01-01" max="2199-12-31" value={day} onChange={event => { setDay(event.target.value); setSaved(false); }} /></label><label className="form-label">时间<input aria-label="本期计划时间" type="time" required disabled={allDay} value={time} onChange={event => { setTime(event.target.value); setSaved(false); }} /></label></div><label className="game-checkbox"><input type="checkbox" checked={allDay} onChange={event => { setAllDay(event.target.checked); setSaved(false); }} />在日历中显示为全天</label><div className="modal-actions"><button type="button" className="button secondary" onClick={onEdit}>编辑重复规则</button><button type="submit" className="button primary">{saved ? '已保存安排' : '保存本期安排'}</button></div></form></div></Modal>;
}
