import { useState } from 'react';
import { Check, Gamepad2, Plus, Repeat2, Trash2 } from 'lucide-react';
import { COLORS, dateKey, minutes, WEEKDAYS } from '../domain';
import { changeProgress, gameDay, gamingData, kindName, KIND_NAMES, localTime, newActivity, newGame, planOccurrence, remainingLabel, removeActivity, removeGame, resolveOccurrence, ruleLabel, saveActivity, saveGame, zoneLabel } from '../gaming';
import type { GameOccurrence, OccurrenceRef } from '../gaming';
import type { ActivityKind, AppData, GameActivity, GameProfile } from '../types';
import { accentStyle, Confirm, Modal } from './ui';

export type GameDialog = { kind: 'games' } | { kind: 'game'; game?: GameProfile; addAfter?: boolean; category?: 'routine' | 'game' } | { kind: 'activity'; activity: GameActivity; isNew: boolean } | { kind: 'occurrence'; ref: OccurrenceRef };
export type DataUpdate = (fn: (data: AppData) => AppData) => boolean;
export function GameDialogs({ dialog, data, now, onDialog, update }: { dialog: GameDialog; data: AppData; now: Date; onDialog: (dialog: GameDialog | null) => void; update: DataUpdate }) {
  const close = () => onDialog(null), gaming = gamingData(data);
  if (dialog.kind === 'games') return <Modal title="周期事务分组" description="普通事务和游戏活动分组管理，各自设置重复周期。" onClose={close} className="game-form-modal"><div className="game-manager">{gaming.games.map(game => <button key={game.id} style={accentStyle(game.color)} onClick={() => onDialog({ kind: 'game', game })}><span className="game-avatar">{game.category === 'routine' ? <Repeat2 size={21} /> : <Gamepad2 size={21} />}</span><span><strong>{game.name}</strong><small>{game.clock === 'local' ? '本机时间' : zoneLabel(game.utcOffset)} · 每天 {game.resetTime} 刷新</small></span><span>编辑</span></button>)}{!gaming.games.length && <p className="game-hint">先添加分组，再创建每天、每周或每月重复的事务。</p>}</div><div className="modal-actions"><button className="button primary" onClick={() => onDialog({ kind: 'game' })}><Plus size={16} />添加分组</button></div></Modal>;
  if (dialog.kind === 'game') return <GameForm key={dialog.game?.id || 'new'} game={dialog.game} category={dialog.category} onClose={close} onSave={game => { if (update(data => saveGame(data, game))) onDialog(dialog.addAfter ? { kind: 'activity', activity: newActivity(game, now), isNew: true } : null); }} onDelete={id => { if (update(data => removeGame(data, id))) close(); }} />;
  if (dialog.kind === 'activity') return <ActivityForm key={dialog.activity.id} activity={dialog.activity} isNew={dialog.isNew} games={gaming.games} now={now} onClose={close} onSave={activity => { if (update(data => saveActivity(data, activity))) close(); }} onDelete={id => { if (update(data => removeActivity(data, id))) close(); }} />;
  const item = resolveOccurrence(data, dialog.ref);
  if (!item) return <Modal title="事务已变更" onClose={close}><p className="confirm-description">该活动已暂停、删除或修改了刷新规则，请从周期事务重新打开。</p><div className="modal-actions"><button className="button primary" onClick={close}>知道了</button></div></Modal>;
  return <OccurrenceForm key={JSON.stringify(dialog.ref)} item={item} now={now} onClose={close} onEdit={() => onDialog({ kind: 'activity', activity: item.activity, isNew: false })} onProgress={count => update(data => changeProgress(data, item.ref, count, new Date()))} onPlan={(day, time) => update(data => planOccurrence(data, item.ref, day, time))} />;
}

function GameForm({ game, category, onClose, onSave, onDelete }: { game?: GameProfile; category?: 'routine' | 'game'; onClose: () => void; onSave: (game: GameProfile) => void; onDelete: (id: string) => void }) {
  const [initial] = useState(() => game || newGame(category || 'routine'));
  const [draft, setDraft] = useState(initial);
  const [confirm, setConfirm] = useState<'discard' | 'delete' | null>(null);
  const patch = (value: Partial<GameProfile>) => setDraft(current => ({ ...current, ...value }));
  const dirty = JSON.stringify(draft) !== JSON.stringify(initial);
  const ruleChanged = game && (game.clock !== draft.clock || game.utcOffset !== draft.utcOffset || game.resetTime !== draft.resetTime || game.weekResetDay !== draft.weekResetDay || game.monthResetDay !== draft.monthResetDay);
  return <><Modal title={game ? '编辑分组' : '添加分组'} description="普通事务默认在本机午夜开启下一周期。" onClose={() => dirty ? setConfirm('discard') : onClose()} className="game-form-modal"><form onSubmit={event => { event.preventDefault(); if (draft.name.trim()) onSave({ ...draft, name: draft.name.trim() }); }}>
    <div className="game-form-scroll"><label className="form-label">分组名称<input data-autofocus aria-label="分组名称" placeholder="例如：生活习惯、学习、游戏名称" required maxLength={40} value={draft.name} onChange={event => patch({ name: event.target.value })} /></label>
    <label className="form-label">分组类型<select aria-label="分组类型" value={draft.category || 'game'} onChange={event => { const category = event.target.value as 'routine' | 'game'; patch({ category, clock: category === 'routine' ? 'local' : 'fixed', resetTime: category === 'routine' ? '00:00' : '04:00' }); }}><option value="routine">普通事务</option><option value="game">游戏活动</option></select></label>
    <div className="form-label">标记颜色<div className="color-choices">{COLORS.map((color, index) => <button type="button" key={color} aria-label={`分组颜色 ${index + 1}`} aria-pressed={color === draft.color} style={{ background: color }} onClick={() => patch({ color })}>{draft.color === color && <Check size={18} />}</button>)}</div></div>
    <label className="form-label">时间基准<select aria-label="时间基准" value={draft.clock || 'fixed'} onChange={event => patch({ clock: event.target.value as 'local' | 'fixed' })}><option value="local">本机时间（跟随系统时区）</option><option value="fixed">固定服务器时区</option></select></label>
    <div className="game-fields"><label className="form-label">服务器时区<select aria-label="服务器时区" disabled={draft.clock === 'local'} value={draft.utcOffset} onChange={event => patch({ utcOffset: Number(event.target.value) })}>{Array.from({ length: 105 }, (_, index) => index * 15 - 720).map(offset => <option key={offset} value={offset}>{zoneLabel(offset)}{offset === 480 ? '（北京时间）' : ''}</option>)}</select></label><label className="form-label">每日刷新时间<input aria-label="每日刷新时间" type="time" required value={draft.resetTime} onChange={event => patch({ resetTime: event.target.value })} /></label>
    <label className="form-label">每周刷新日<select aria-label="每周刷新日" value={draft.weekResetDay} onChange={event => patch({ weekResetDay: Number(event.target.value) })}>{[1, 2, 3, 4, 5, 6, 0].map(day => <option key={day} value={day}>星期{WEEKDAYS[day]}</option>)}</select></label><label className="form-label">每月刷新日<select aria-label="每月刷新日" value={draft.monthResetDay} onChange={event => patch({ monthResetDay: Number(event.target.value) })}>{Array.from({ length: 31 }, (_, index) => <option key={index} value={index + 1}>每月 {index + 1} 日</option>)}</select></label></div>
    <p className="game-hint">每周、每月均在上方时间开启新周期。29–31 日在短月份使用月末。固定服务器时区不跟随夏令时。</p>
    {ruleChanged && <p className="game-rule-notice">修改刷新规则后，该分组的事务将按新周期重新计数。此前完成记录仍会保留。</p>}</div>
    <div className="modal-actions">{game && <button type="button" className="button text-danger" onClick={() => setConfirm('delete')}><Trash2 size={16} />删除分组</button>}<button className="button primary" type="submit" disabled={!draft.name.trim()}>保存分组</button></div>
  </form></Modal>{confirm && <Confirm title={confirm === 'delete' ? '删除这个分组？' : '放弃未保存的更改？'} description={confirm === 'delete' ? '该分组的全部事务和完成记录都会删除。' : '离开后，本次编辑的内容不会保存。'} action={confirm === 'delete' ? '删除分组' : '放弃更改'} danger={confirm === 'delete'} onClose={() => setConfirm(null)} onConfirm={() => confirm === 'delete' ? onDelete(game!.id) : onClose()} />}</>;
}

function ActivityForm({ activity, isNew, games, now, onClose, onSave, onDelete }: { activity: GameActivity; isNew: boolean; games: GameProfile[]; now: Date; onClose: () => void; onSave: (activity: GameActivity) => void; onDelete: (id: string) => void }) {
  const [draft, setDraft] = useState(() => structuredClone(activity));
  const [confirm, setConfirm] = useState<'discard' | 'delete' | null>(null);
  const patch = (value: Partial<GameActivity>) => setDraft(current => ({ ...current, ...value }));
  const game = games.find(item => item.id === draft.gameId)!;
  const dirty = JSON.stringify(draft) !== JSON.stringify(activity);
  const scheduleMode = draft.timeWindow ? 'window' : draft.anytime ? 'anytime' : 'fixed';
  const offset = (time: string) => (minutes(time) - minutes(game.resetTime) + 1440) % 1440;
  const windowError = draft.timeWindow && offset(draft.timeWindow.latest) < offset(draft.timeWindow.earliest) ? '最晚时间不能早于本周期的最早时间。' : '';
  const ruleChanged = !isNew && (draft.gameId !== activity.gameId || draft.kind !== activity.kind || [...draft.weekdays].sort().join() !== [...activity.weekdays].sort().join());
  return <><Modal title={isNew ? '新建周期事务' : '编辑重复规则'} description="按刷新周期重复，完成次数每期独立记录。" onClose={() => dirty ? setConfirm('discard') : onClose()} className="game-form-modal"><form onSubmit={event => { event.preventDefault(); if (!windowError && draft.title.trim() && (draft.kind !== 'material' || draft.weekdays.length)) onSave(draft); }}>
    <div className="game-form-scroll"><label className="form-label">事务名称<input data-autofocus aria-label="事务名称" required maxLength={150} placeholder="例如：阅读、每周复盘、材料收集" value={draft.title} onChange={event => patch({ title: event.target.value })} /></label>
    <div className="game-fields"><label className="form-label">所属分组<select aria-label="所属分组" value={draft.gameId} onChange={event => { const next = games.find(game => game.id === event.target.value)!; patch({ gameId: next.id, startDate: next.id === activity.gameId ? activity.startDate : gameDay(next, now) }); }}>{games.map(game => <option key={game.id} value={game.id}>{game.name}</option>)}</select></label><label className="form-label">重复规则<select aria-label="重复规则" value={draft.kind} onChange={event => patch({ kind: event.target.value as ActivityKind })}>{Object.entries(game.category === 'routine' ? { daily: '每天', material: '指定星期', weekly: '每周', monthly: '每月' } : KIND_NAMES).map(([kind, name]) => <option key={kind} value={kind}>{name}</option>)}</select></label></div>
    {draft.kind === 'material' && <fieldset className="weekday-field"><legend>{game.category === 'routine' ? '执行星期' : '材料本开放日'}</legend><div className="weekday-choices">{[1, 2, 3, 4, 5, 6, 0].map(day => <button type="button" key={day} aria-label={`星期${WEEKDAYS[day]}${game.category === 'routine' ? '执行' : '开放'}`} aria-pressed={draft.weekdays.includes(day)} onClick={() => patch({ weekdays: draft.weekdays.includes(day) ? draft.weekdays.filter(value => value !== day) : [...draft.weekdays, day] })}>周{WEEKDAYS[day]}</button>)}</div>{!draft.weekdays.length && <p className="field-error">至少选择一个星期。</p>}</fieldset>}
    <div className="game-fields"><label className="form-label">{draft.kind === 'material' ? game.category === 'routine' ? '每个执行日目标' : '每次开放日目标' : '每个周期目标'}<span className="game-unit-input"><input aria-label="目标次数" type="number" required min={1} max={99} value={draft.target} onChange={event => patch({ target: Number(event.target.value) })} /><span>次</span></span></label><label className="form-label">时间安排<select aria-label="周期时间安排" value={scheduleMode} onChange={event => patch({ anytime: event.target.value === 'anytime', timeWindow: event.target.value === 'window' ? { earliest: '09:00', latest: '22:00' } : undefined })}><option value="anytime">不限时间</option><option value="window">时间窗口</option><option value="fixed">固定时间</option></select></label>
    {scheduleMode === 'fixed' && <label className="form-label">计划时间 · {game.clock === 'local' ? '本机' : zoneLabel(game.utcOffset)}<input aria-label="活动计划时间" type="time" required value={draft.planTime} onChange={event => patch({ planTime: event.target.value })} /></label>}
    {draft.timeWindow && <><label className="form-label">最早时间<input aria-label="周期最早时间" type="time" required value={draft.timeWindow.earliest} onChange={event => patch({ timeWindow: { ...draft.timeWindow!, earliest: event.target.value } })} /></label><label className="form-label">最晚时间<input aria-label="周期最晚时间" type="time" required value={draft.timeWindow.latest} onChange={event => patch({ timeWindow: { ...draft.timeWindow!, latest: event.target.value } })} /></label></>}
    {draft.kind === 'weekly' && <label className="form-label">每周计划日<select aria-label="每周计划日" value={draft.planWeekday} onChange={event => patch({ planWeekday: Number(event.target.value) })}>{[1, 2, 3, 4, 5, 6, 0].map(day => <option key={day} value={day}>星期{WEEKDAYS[day]}</option>)}</select></label>}
    {draft.kind === 'monthly' && <label className="form-label">每月计划日<select aria-label="每月计划日" value={draft.planMonthDay} onChange={event => patch({ planMonthDay: Number(event.target.value) })}>{Array.from({ length: 31 }, (_, index) => <option key={index} value={index + 1}>{index + 1} 日</option>)}</select></label>}
    {scheduleMode === 'fixed' && <label className="form-label">单次预计用时<span className="game-unit-input"><input aria-label="单次预计用时" type="number" min={1} max={720} required value={draft.minutes} onChange={event => patch({ minutes: Number(event.target.value) })} /><span>分钟</span></span></label>}{game.category !== 'routine' && <label className="form-label">单次体力消耗<span className="game-unit-input"><input aria-label="单次体力消耗" type="number" min={0} max={999} required value={draft.energy} onChange={event => patch({ energy: Number(event.target.value) })} /><span>点</span></span></label>}</div>
    {windowError && <p className="field-error" role="alert">{windowError}</p>}
    <p className="game-hint">每期独立记录次数，{game.resetTime} 刷新。{scheduleMode !== 'fixed' ? '不指定起始时刻，显示在日历“待安排”区；之后可单独安排本期。' : '计划会自动换算到本机日历。'}{draft.kind === 'monthly' ? '短月份使用月末。' : ''}</p>
    <label className="form-label">备注<textarea aria-label="活动备注" rows={3} maxLength={5000} placeholder="添加备注…" value={draft.notes} onChange={event => patch({ notes: event.target.value })} /></label>
    {ruleChanged && <p className="game-rule-notice">执行日、重复规则或分组变更后，将按新周期计数。修改名称、目标或计划时间会保留进度。</p>}</div>
    <div className="modal-actions">{!isNew && <button type="button" className="button text-danger" onClick={() => setConfirm('delete')}><Trash2 size={16} />删除事务</button>}<button className="button primary" type="submit" disabled={!!windowError || !draft.title.trim() || (draft.kind === 'material' && !draft.weekdays.length)}>{isNew ? '创建事务' : '保存事务'}</button></div>
  </form></Modal>{confirm && <Confirm title={confirm === 'delete' ? '删除这个事务？' : '放弃未保存的更改？'} description={confirm === 'delete' ? '重复规则及其所有完成记录都会删除。' : '离开后，本次编辑的内容不会保存。'} action={confirm === 'delete' ? '删除事务' : '放弃更改'} danger={confirm === 'delete'} onClose={() => setConfirm(null)} onConfirm={() => confirm === 'delete' ? onDelete(activity.id) : onClose()} />}</>;
}

export function ProgressControls({ item, now, onChange }: { item: GameOccurrence; now: Date; onChange: (count: number) => void }) {
  const active = now >= item.start && now < item.end && gameDay(item.game, now) >= item.activity.startDate;
  return <div className="game-progress-controls"><button aria-label={`减少完成次数 ${item.activity.title}`} disabled={!active || !item.count} onClick={() => onChange(item.count - 1)}>−</button><span aria-label="完成进度">{item.count}<small> / {item.activity.target}</small></span><button aria-label={`增加完成次数 ${item.activity.title}`} disabled={!active || item.count >= item.activity.target} onClick={() => onChange(item.count + 1)}>＋</button><button className={`game-complete ${item.count >= item.activity.target ? 'is-complete' : ''}`} disabled={!active} onClick={() => onChange(item.count >= item.activity.target ? 0 : item.activity.target)}><Check size={15} />{item.count >= item.activity.target ? '已完成' : '完成'}</button></div>;
}

function OccurrenceForm({ item, now, onClose, onEdit, onProgress, onPlan }: { item: GameOccurrence; now: Date; onClose: () => void; onEdit: () => void; onProgress: (count: number) => void; onPlan: (day: string, time: string | null) => boolean }) {
  const [day, setDay] = useState(dateKey(item.plannedAt));
  const [time, setTime] = useState(localTime(item.plannedAt));
  const [allDay, setAllDay] = useState(item.allDay);
  const [saved, setSaved] = useState(false);
  const format = (at: Date) => `${dateKey(at)} ${localTime(at)}`;
  return <Modal title="本期安排" description={`${item.game.name} · ${kindName(item.activity, item.game)}`} onClose={onClose} className="game-form-modal"><div className="game-occurrence-detail" style={accentStyle(item.game.color)}><h3>{item.activity.title}</h3><p className="game-hint">{ruleLabel(item.activity, item.game)} · 每次 {item.activity.minutes} 分钟{item.game.category !== 'routine' && item.activity.energy ? ` · ${item.activity.energy} 体力` : ''}</p><div className="game-cycle-info"><span>本期开放（本机时间）</span><strong>{format(item.start)} — {format(item.end)}</strong><small>{now < item.start ? '尚未开放，可提前安排时间' : remainingLabel(item.end, now)}</small></div><ProgressControls item={item} now={now} onChange={onProgress} />{item.activity.notes && <p className="game-detail-notes">{item.activity.notes}</p>}
    <form onSubmit={event => { event.preventDefault(); if (onPlan(day, allDay ? null : time)) setSaved(true); }}><h4>本期计划</h4>{item.timeWindow && <p className="window-notice">可安排：{format(item.timeWindow.start)} — {format(item.timeWindow.end)}</p>}<p className="game-hint">按本机时区安排，仅调整这一次；请放在上方开放区间内。</p><div className="game-fields"><label className="form-label">日期<input aria-label="本期计划日期" required type="date" min="1900-01-01" max="2199-12-31" value={day} onChange={event => { setDay(event.target.value); setSaved(false); }} /></label><label className="form-label">时间<input aria-label="本期计划时间" type="time" required disabled={allDay} value={time} onChange={event => { setTime(event.target.value); setSaved(false); }} /></label></div><label className="game-checkbox"><input type="checkbox" checked={allDay} onChange={event => { setAllDay(event.target.checked); setSaved(false); }} />暂不指定时刻（显示在待安排区）</label><div className="modal-actions"><button type="button" className="button secondary" onClick={onEdit}>编辑重复规则</button><button type="submit" className="button primary">{saved ? '已保存安排' : '保存本期安排'}</button></div></form></div></Modal>;
}
